module.exports={
  "facebook_api_key"      :     "",
  "facebook_api_secret"   :     "",
  "callback_url"          :     "",
  "use_database"          :     "",
  "host"                  :     "",
  "username"              :     "",
  "password"              :     "",
  "database"              :     "",
  "db_host"		  :	"",
  "db_user"		  :	"",
  "db_password"		  :	"",
  "db_database"		  :	"",
  "gmail_uname"           :     "",
  "gmail_pwd"             : 	"",
  "yelp_consumer_key"	  :  	"", 
  "yelp_consumer_secret"  :  	"",
  "yelp_token"		  :  	"",
  "yelp_token_secret"	  :  	""
}
